spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: 123
springdoc:
  swagger-ui:
    server.list: http://localhost:${server.port}${server.servlet.context-path}