global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090

  - job_name: api
    metrics_path: /api/client/actuator/prometheus
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
          - client-api:8090